manifest:
  remotes:
    # zmk official
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # testing mouse keys
    - name: mousekeys
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: mousekeys
      revision: feat/pointers-move-scroll
      import: app/west.yml
  self:
    path: config
